# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"
  - "ios >= 7"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "dist"
  # Paths to static assets that aren't images, SCSS, or JavaScript
  assets:
    - "src/**/*"
    - "!src/{img,js,scss}/**/*"
    - "!src/scss"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    #- "node_modules/materialize-css/sass"
  # Paths to JavaScript entry points for webpack to bundle modules
  entries:
    - "src/js/particles.js"
    - "src/js/terminal.js"
